// Objects.
const BACKGROUND_WIDTH = 800;
const BACKGROUND_HEIGHT = 600;

const HERO_WIDTH = BACKGROUND_WIDTH / 20;
const HERO_HEIGHT = BACKGROUND_HEIGHT / 9;

const ENEMY_WIDTH = BACKGROUND_WIDTH / 20;
const ENEMY_HEIGHT = BACKGROUND_HEIGHT / 9;

var HERO_SPEED = 5;

var BACKGROUND_SPEED = 3;
var ENEMY_SPEED = BACKGROUND_SPEED + 1;

const SCORE_AND_LIFE_FONT_SIZE = 32;

const GAME_OVER_FONT_SIZE = 72;


